In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from xgboost import XGBClassifier
import warnings
warnings.filterwarnings('ignore')

In [8]:
import pandas as pd

# Load the data
train_df = pd.read_csv('Assignment_Train.csv')
test_df = pd.read_csv('Assignment_Test.csv')

In [11]:
def preprocess_data(df):
    # Convert date column to datetime with the correct format
    df['APPLICATION LOGIN DATE'] = pd.to_datetime(df['APPLICATION LOGIN DATE'], format='%m/%d/%Y', errors='coerce')
    
    # Extract features from date
    df['APPLICATION_MONTH'] = df['APPLICATION LOGIN DATE'].dt.month
    df['APPLICATION_DAY'] = df['APPLICATION LOGIN DATE'].dt.day
    df['APPLICATION_DAYOFWEEK'] = df['APPLICATION LOGIN DATE'].dt.dayofweek
    
    # # Handle categorical variables
    # categorical_features = df.select_dtypes(include=['object']).columns
    
    # for feature in categorical_features:
    #     if feature in df.columns:
    #         df[feature] = df[feature].astype('category')
    
    # Handle boolean features
    boolean_features = [col for col in df.columns if col.startswith('Phone Social Premium.')]
    for feature in boolean_features:
        df[feature] = df[feature].fillna(0).astype(int)
    
    # Handle numerical features
    numerical_features_int = df.select_dtypes(include=['int64']).columns
    


    # Impute missing values in numerical features
    num_imputer = SimpleImputer(strategy='mean')
    for feature in numerical_features_int:
        if feature in df.columns:
            df[[feature]] = num_imputer.fit_transform(df[[feature]])
    
    # # Impute missing values in categorical features
    # cat_imputer = SimpleImputer(strategy='most_frequent')
    # for feature in categorical_features:
    #     if feature in df.columns:
    #         df[feature] = cat_imputer.fit_transform(df[[feature]])
    
    return df

In [12]:
preprocess_data(train_df)
preprocess_data(test_df)
# train_df['Cibil Score'] = pd.to_numeric(train_df['Cibil Score'], errors='coerce')
# test_df['Cibil Score'] = pd.to_numeric(test_df['Cibil Score'], errors='coerce')
# print(train_df.isna().sum(),train_df.dtypes)

,UID,DEALER ID,APPLICATION LOGIN DATE,HDB BRANCH NAME,HDB BRANCH STATE,FIRST NAME,MIDDLE NAME,LAST NAME,mobile,AADHAR VERIFIED,...,Phone Social Premium.toi,Phone Social Premium.whatsapp,Phone Social Premium.yatra,Phone Social Premium.zoho,phone_digitalage,phone_nameMatchScore,phone_phoneFootprintStrengthOverall,APPLICATION_MONTH,APPLICATION_DAY,APPLICATION_DAYOFWEEK
0,1.844045e+18,105615.0,NaT,HUBLI-SF,NaN,VENUGOPAL,H,BHARADHVAJ,7.019760e+09,NO,...,0,0,0,0,676.0,100.000000,Medium,NaN,NaN,NaN
1,1.840349e+18,91593.0,2022-07-14,SATNA-SF,MADHYA PRADESH,SHIVDHAR,NaN,CHAUDHARY,7.697885e+09,NO,...,0,0,0,0,897.0,-1.000000,Low,7.0,14.0,3.0
2,1.488103e+18,74152.0,NaT,LUCKNOW-SF,UTTAR PRADESH,MANISH,NaN,VERMA,8.840080e+09,NO,...,0,1,0,0,839.0,100.000000,Medium,NaN,NaN,NaN
3,5.555299e+17,110164.0,2022-07-13,KOLLAM-SF,KERALA,DEEPU,RAVEENDRAN,RAVEENDRAN,8.089277e+09,NO,...,0,0,0,0,2050.0,-1.000000,Low,7.0,13.0,2.0
4,1.010213e+18,113037.0,NaT,PURI-SF,ORISSA,AKASHA,NaN,PRADHAN,9.337512e+09,NO,...,0,0,0,0,-1.0,-1.000000,Very Low,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1.595862e+18,110697.0,2022-07-25,LUCKNOW-SF,NaN,PARVESH,KUMAR,NaN,8.542832e+09,NO,...,1,0,0,0,1998.0,81.363636,Medium,7.0,25.0,0.0
1996,8.798897e+17,107225.0,2022-07-21,SHUJALPUR-SF,MADHYA PRADESH,RAMCHARAN,NaN,PAL,8.959152e+09,NO,...,1,0,0,0,277.0,-1.000000,Medium,7.0,21.0,3.0
1997,2.429095e+17,92743.0,2022-07-19,NOIDA-SF,UTTAR PRADESH,SANTOSH,NaN,PRASAD,8.130179e+09,NO,...,1,0,0,0,540.0,18.695652,High,7.0,19.0,1.0
1998,1.387256e+17,193608.0,NaT,DARBHANGA-SF,BIHAR,MOHAN,NaN,PANDIT,7.070956e+09,NO,...,0,1,0,0,1671.0,-1.000000,Low,NaN,NaN,NaN
1999,1.680321e+18,84909.0,2022-07-24,SUPAUL-SF,BIHAR,MOHAMMAD,NIJAM,NADAF,7.633088e+09,NO,...,0,0,0,0,1988.0,-1.000000,Low,7.0,24.0,6.0